FROM nginx:1.27-alpine

COPY nginx.conf /tmp/default.conf

RUN cat /tmp/default.conf > /etc/nginx/conf.d/default.conf \
    && chown root:root /etc/nginx/conf.d/default.conf \
    && chmod 644 /etc/nginx/conf.d/default.conf \
    && rm -f /tmp/default.conf
